ALTER TABLE `truTrustPayments_transaction`
	MODIFY `OXID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `OXORDERID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `TRUUPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	MODIFY `TRUVERSION` int(11) DEFAULT '0';
	
ALTER TABLE `truTrustPayments_completionjob`
	MODIFY `OXID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `OXORDERID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `TRUUPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
	
ALTER TABLE `truTrustPayments_voidjob`
	MODIFY `OXID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `OXORDERID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `TRUUPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
	
ALTER TABLE `truTrustPayments_cron`
	MODIFY `OXID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '';

ALTER TABLE `truTrustPayments_refundjob`
	MODIFY `OXID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `OXORDERID` char(32) CHARSET latin1 COLLATE latin1_general_ci DEFAULT '',
	MODIFY `TRUUPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `truTrustPayments_alert`
	MODIFY `TRUUPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS `truTrustPayments_token` (
  `TRUTOKENID` bigint(20) unsigned NOT NULL,
  `TRUSTATE` varchar(255) NOT NULL,
  `TRUSPACEID` bigint(20) unsigned NOT NULL,
  `TRUNAME` longtext,
  `TRUCUSTOMERID` bigint(20) unsigned NOT NULL,
  `TRUPAYMENTMETHODID` bigint(20) unsigned NOT NULL,
  `TRUCONNECTORID` bigint(20) unsigned NOT NULL,
  `TRUUPDATED` TIMESTAMP NOT NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`TRUTOKENID`),
  INDEX (`TRUTOKENID`, `TRUSPACEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;